### ISSUE TITLE
TypeError Nagios actionExecutor.py

### ISSUE THREAD

**Issue by aroelo** [opsgenie/oec-scripts#100]
We currently get this error when the script tries to get the histogram image, but can't find it.
`Reason: Err: exit status 1, Stderr: Traceback (most recent call last): File "/home/opsgenie/oec/scripts/actionExecutor.py", line 418, in <module> main() File "/home/opsgenie/oec/scripts/actionExecutor.py", line 367, in main attach("service") File "/home/opsgenie/oec/scripts/actionExecutor.py", line 262, in attach alert_histogram = get_alert_histogram(entity) File "/home/opsgenie/oec/scripts/actionExecutor.py", line 116, in get_alert_histogram return get_image(url, entity) File "/home/opsgenie/oec/scripts/actionExecutor.py", line 108, in get_image response.status_code) + "Reason: " + content) TypeError: must be str, not bytes`

The 'response.content' that is returned is in a binary format, which gives a TypeError when it tries to log/print the warning message that the image can not be found.

I created https://github.com/opsgenie/oec-scripts/pull/99 for a fix

**Comment by ozlemmcokuk** [comment]
The new package has been released. Please see Nagios-1.1.5_oec-1.1.4
