### ISSUE TITLE
icinga2ActionExecutor.py: Do not write to current directory (and clean up after yourself)

### ISSUE THREAD

**Issue by 5nafu** [opsgenie/oec-scripts#11]
The icinga2ActionExecutor.py ([Line 110](https://github.com/opsgenie/oec-scripts/blob/a977aa1a295b34000a0915ea1afe575c6fab5042/Icinga2/icinga2ActionExecutor.py#L110)) writes temporary files into the current working directory, which is not necessarily writable.

Additionally the temporary files will not be cleaned up after sending them to opsgenie.

It would be better to use a proper temp directory for storage of the files cleaning up the tempdir after finishing.

**Comment by ahalac-atlassian** [comment]
Hi @5nafu, you can track the progress about the issue from [this ticket](https://jira.atlassian.com/browse/OPSGENIE-1091)
