### ISSUE TITLE
Do not send a password to a logfile

### ISSUE THREAD

**Issue by 5nafu** [opsgenie/oec-scripts#14]
A password is a secret which should never be exposed to STDOUT or a log file. 
Unfortunately in https://github.com/opsgenie/oec-scripts/blob/a977aa1a295b34000a0915ea1afe575c6fab5042/Icinga2/icinga2ActionExecutor.py#L328
the Password is explicitly logged and in the default oec integration written to a log file.

Please fix by removing line 328 in the  icinga2ActionExecutor.py

**Comment by cglrkn** [comment]
We fixed it. Thanks for the contribution.
