### ISSUE TITLE
jiraServiceDeskActionExecutor.py Line 45 throws an error

### ISSUE THREAD

**Issue by jameseholt** [opsgenie/oec-scripts#2]
`response = requests.get(jira_url, None, headers=request_headers, auth=token, timeout=timeout)`
_should be_ 
`response = requests.get(jira_url, headers=request_headers, auth=token, timeout=timeout)`

**Comment by cemkucuk** [comment]
Hey @jameseholt, thank you for your attention. We've tested this script, and it is working as desired. Can you share the error output? Also, which version of Python you are using?

**Comment by jameseholt** [comment]
Python 2.7.5.  Error is something like "get() requires exactly 1 argument (received 5)"

**Comment by cemkucuk** [comment]
We have no support for Python 2.x versions for scripts, could you try any version with 3.x?

**Comment by jameseholt** [comment]
Noted thanks @cemkucuk Suggest you update your OEC documentation accordingly.

**Comment by cemkucuk** [comment]
Sure @jameseholt, thanks for the feedback.
