### ISSUE TITLE
jiraServiceDeskActionExecutor.py get_transition_id tries to get the ID of the destination state, not the transition itself

### ISSUE THREAD

**Issue by jameseholt** [opsgenie/oec-scripts#3]
The code (lines 49-52) is:
`        for transition in transition_list:
            to = transition['to']
            if transition_name == to['name']:
                transition_id = transition['id']`
_it should be:_
`        for transition in transition_list:
            if transition_name == transition['name']:
                transition_id = transition['id']`

**Comment by cemkucuk** [comment]
Hey @jameseholt, we are checking the name field under the _to_ field instead of _transition_ field, and it's working as demanded. Can you explain in detail?

**Comment by jameseholt** [comment]
Can you please confirm you are testing this by firing a resolveIssue action?  The createIssue and commentIssue don't call the get_transition_id function.

**Comment by cemkucuk** [comment]
@jameseholt, I will create an analyze ticket for it to our engineering team. During this time, you can use your own modified Python script.

**Comment by cemkucuk** [comment]
@jameseholt, we have investigated the issue with testing from scratch, and everything seems well. If the script is still not working for you, you can use your edited script.
