### ISSUE TITLE
Close Issue not working

### ISSUE THREAD

**Issue by mkempken** [opsgenie/oec-scripts#7]
When I try to close a Jira Issue this error pops up.

ESC[37mDEBUESC[0m[2019-09-30T09:17:15.926190112Z] Action[resolveIssue] execution of message[6086cc9b-e604-4fdb-97d9-7592a598b312] with alertId[22e461cd-1d27-4335-a22c-da8a14926eba-1569834735313] failed: exit status 1 Stderr: Traceback (most recent call last):
  File "/var/opsgenie/oec/jiraActionExecutor.py", line 215, in <module>
    main()
  File "/var/opsgenie/oec/jiraActionExecutor.py", line 132, in main
    "id": get_transition_id(headers, result_url, "Resolved")
TypeError: get_transition_id() takes exactly 4 arguments (3 given)

line 46 of def get_transition_id is causing the error
 response = requests.get(jira_url, None, headers=request_headers, auth=token, timeout=timeout)

**Comment by cglrkn** [comment]
We fixed the bug. Thanks for reporting it!
