### ISSUE TITLE
Dots and hyphens in "hostName" should not be removed

### ISSUE THREAD

**Issue by scorillo** [opsgenie/oec-scripts#85]
Introduced by #82 at [this line](https://github.com/opsgenie/oec-scripts/commit/2d9f6eea58a8539adf5096c643517e47c24f4fba#diff-0299594933eeb2809a34a94b149ef894028092a8be81219c586eed5937f3fe94R313)

**Comment by ahalac-atlassian** [comment]
Hi @scorillo, you can track the progress about the issue from [this ticket](https://jira.atlassian.com/browse/OPSGENIE-1090)

**Comment by ozlemmcokuk** [comment]
We released the new package [Zabbix-1.1.8_oec-1.1.4] by reverting the removal of special characters for some of the fields that are mainly shown in the alert message and description.
