### ISSUE TITLE
Cannot modify log path for send2opsgenie (zabbix)

### ISSUE THREAD

**Issue by krisavi** [opsgenie/oec-scripts#88]
The issue is due to logging initialization before loading values from config. Since the config is not loaded in before logging initialization, default value will be used.

https://github.com/opsgenie/oec-scripts/blob/ad551be493c9e3ef9dac5051e5c6e4839b01e8d7/Zabbix/opsgenie-zabbix/send2opsgenie.go#L50
https://github.com/opsgenie/oec-scripts/blob/ad551be493c9e3ef9dac5051e5c6e4839b01e8d7/Zabbix/opsgenie-zabbix/send2opsgenie.go#L52

**Comment by ahalac-atlassian** [comment]
Hi @krisavi, you can track the progress from [this ticket](https://jira.atlassian.com/browse/OPSGENIE-1087)

**Comment by ozlemmcokuk** [comment]
We released a new package [Zabbix-1.1.8_oec-1.1.4] by reverting the removal of special characters for some of the fields that are mainly shown in the alert message and description.

**Comment by ozlemmcokuk** [comment]
The new package has been released. Please see Zabbix-1.1.9_oec-1.1.4
