### ISSUE TITLE
Oec

### ISSUE THREAD

**Issue by HendarMoko** [opsgenie/oec-scripts#89]

**Comment by ahalac-atlassian** [comment]
You can find open bugs and suggestions for OEC on our [public issue tracker](https://jira.atlassian.com/browse/OPSGENIE-803?jql=project%3DOPSGENIE%20AND%20component%20in%20(%22OEC%20-%20Configuration%22%2C%20%22OEC%20-%20Installation%22)%20and%20resolution%20is%20EMPTY). If you are experiencing an issue with OEC, or if you want to raise a new bug or suggestion you can reach out [Opsgenie support.](https://support.atlassian.com/contact/#/)
