### ISSUE TITLE
Acknowledging from OpsGenie to Zabbix not working

### ISSUE THREAD

**Issue by ghost** [opsgenie/oec-scripts#9]
Hi.

I'm tryng to configure oec to aknowldge alerts on zabbix as they're aknowledge on opsgenie

my zabbix version is 4.4.4

i'm using the script zabbixActionExecutorForZabbix4.py

and this is my oec config.json

```
{
  "apiKey": "omitted",
  "baseUrl": "https://api.eu.opsgenie.com",
  "logLevel": "DEBUG",
  "globalFlags": {
    "command_url": "omitted",
    "user": "omitted",
    "password": "omitted"
  },
  "actionMappings": {
    "Acknowledge": {
      "filepath": "/home/opsgenie/oec/zabbixActionExecutorForZabbix4.py",
      "sourceType": "local",
      "stdout": "/home/opsgenie/oec/oec.log"
    }
  },
  "pollerConf": {
    "pollingWaitIntervalInMillis": 100,
    "visibilityTimeoutInSec": 30,
    "maxNumberOfMessages": 10
  },
  "poolConf": {
    "maxNumberOfWorker": 12,
    "minNumberOfWorker": 4,
    "monitoringPeriodInMillis": 15000,
    "keepAliveTimeInMillis": 6000,
    "queueSize": 0
  }
}
```

And i receive this errror:

```
Jan 02 16:31:01 zabbix.arezzo.diennea.lan OpsgenieEdgeConnector[92388]: DEBU[2020-01-02T16:31:01.431393742+01:00] Action[Acknowledge] execution of message[b2975768-8c75-4b70-8907-fccd0f9f07c0] with entityId[2e05449f-7831-4be7-9c51-2192ae2187f8-1577979001914] failed: exit status 1 Stderr: Traceback (most recent call last):
Jan 02 16:31:01 zabbix.arezzo.diennea.lan OpsgenieEdgeConnector[92388]: File "/home/opsgenie/oec/zabbixActionExecutorForZabbix4.py", line 139, in <module>
Jan 02 16:31:01 zabbix.arezzo.diennea.lan OpsgenieEdgeConnector[92388]: main()
Jan 02 16:31:01 zabbix.arezzo.diennea.lan OpsgenieEdgeConnector[92388]: File "/home/opsgenie/oec/zabbixActionExecutorForZabbix4.py", line 110, in main
Jan 02 16:31:01 zabbix.arezzo.diennea.lan OpsgenieEdgeConnector[92388]: "eventids": queue_message["alert"]["details"]["eventId"],
Jan 02 16:31:01 zabbix.arezzo.diennea.lan OpsgenieEdgeConnector[92388]: KeyError: 'details'
```

could you help me please?

**Comment by Cobra1978** [comment]
Ok, i solved the probem: the scirpt part ta takes the evnetId from details is:

`"eventids": queue_message["alert"]["details"]["eventId"],`

But details are in the 'data' structure of the response, so the line should be:

`"eventids": alert_response.json()['data']['details']['eventId'],`

So it works

Please tell me if this is not right and, if this is the case, find a proper solution.

**Comment by trenta** [comment]
I tried this change and got the following output:

`Action[Acknowledge] execution of message[8aa8044b-4557-4d5d-9434-855ff42aa6c6] with entityId[6adbfcd7-90b6-477c-ad84-bc2348ab8c88-1580789819750] failed: exit status 1 Stderr: Traceback (most recent call last):
  File "/usr/local/bin/zabbixActionExecutorForZabbix4.py", line 138, in <module>
    main()
  File "/usr/local/bin/zabbixActionExecutorForZabbix4.py", line 115, in main
    auth = login_to_zabbix(username, password, url)
  File "/usr/local/bin/zabbixActionExecutorForZabbix4.py", line 55, in login_to_zabbix
    logging.debug(LOG_PREFIX + " login response: " + str(login_result.status_code) + " " + str(login_result.json()))
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

**Comment by trenta** [comment]
I've tried this fix and it works for me also.  Thanks.

**Comment by JohnBelliveauNB** [comment]
This is not working for me. 
OpsgenieEdgeConnector[14985]: "eventids": alert_response.json()['data']['details']['eventId'],
OpsgenieEdgeConnector[14985]: KeyError: 'eventId'

From the Opsgenie activity log:
Executed [Acknowledge] action via OEC[integrationId: 67373b3a-9f21-412d-aee6-08817e3fd186 integrationType: Zabbix] with errors. Reason: Err: exit status 1, Stderr: Traceback (most recent call last): File "/home/opsgenie/oec/scripts/actionExecutorForZabbix4.py", line 138, in <module> main() File "/home/opsgenie/oec/scripts/actionExecutorForZabbix4.py", line 109, in main "eventids": alert_response.json()['data']['details']['eventId'], KeyError: 'eventId'

**Comment by ahalac-atlassian** [comment]
Hi @ghost, you can track the progress about the issue from [this ticket](https://jira.atlassian.com/browse/OPSGENIE-1095)

**Comment by emelkomurcu** [comment]
The problem is fixed. Please check the newest version of zabbix release  
Zabbix-1.1.10_oec-1.1.4
